
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { debounce } from '@/lib/utils';

const SUPABASE_URL = "https://gjrheltyxjilxcphbzdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqcmhlbHR5eGppbHhjcGhiemRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MDkyNzcsImV4cCI6MjA1ODA4NTI3N30.T1dnULbKmLGr7PsEvONlnQeuSEPz19706325o-3HD18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'supabase.auth.token',
    storage: localStorage,
    detectSessionInUrl: false, // Prevents potential redirect loops
    flowType: 'pkce' // More secure flow type
  },
  realtime: {
    params: {
      eventsPerSecond: 2 // Limit events per second for realtime subscribers
    }
  },
  global: {
    // Add better retry logic for network requests
    headers: {
      'X-Client-Info': 'lovable-app/1.0.0'
    },
    fetch: (url, options) => {
      // Custom fetch with timeout to prevent hanging requests
      const timeoutPromise = new Promise((_, reject) => {
        setTimeout(() => reject(new Error('Request timeout')), 10000);
      });
      
      return Promise.race([
        fetch(url, options),
        timeoutPromise
      ]) as Promise<Response>;
    }
  }
});

// Create a utility to help with managing subscriptions
export class SubscriptionManager {
  private static subscriptions: Map<string, { channel: any, count: number }> = new Map();
  
  // Get or create a subscription with reference counting
  static getSubscription(channelName: string, factory: () => any): any {
    const existing = this.subscriptions.get(channelName);
    
    if (existing) {
      existing.count++;
      return existing.channel;
    }
    
    const channel = factory();
    this.subscriptions.set(channelName, { channel, count: 1 });
    return channel;
  }
  
  // Release a subscription, removing if no more references
  static releaseSubscription(channelName: string): void {
    const existing = this.subscriptions.get(channelName);
    if (!existing) return;
    
    existing.count--;
    
    if (existing.count <= 0) {
      supabase.removeChannel(existing.channel);
      this.subscriptions.delete(channelName);
      console.log(`Released subscription: ${channelName}`);
    }
  }
}
